// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

#ifndef PROTOBUF_connector_2eproto__INCLUDED
#define PROTOBUF_connector_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_connector_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsCS_PingImpl();
void InitDefaultsCS_Ping();
void InitDefaultsSC_RetPingImpl();
void InitDefaultsSC_RetPing();
inline void InitDefaults() {
  InitDefaultsCS_Ping();
  InitDefaultsSC_RetPing();
}
}  // namespace protobuf_connector_2eproto
namespace proto {
class CS_Ping;
class CS_PingDefaultTypeInternal;
extern CS_PingDefaultTypeInternal _CS_Ping_default_instance_;
class SC_RetPing;
class SC_RetPingDefaultTypeInternal;
extern SC_RetPingDefaultTypeInternal _SC_RetPing_default_instance_;
}  // namespace proto
namespace proto {

// ===================================================================

class CS_Ping : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.CS_Ping) */ {
 public:
  CS_Ping();
  virtual ~CS_Ping();

  CS_Ping(const CS_Ping& from);

  inline CS_Ping& operator=(const CS_Ping& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CS_Ping(CS_Ping&& from) noexcept
    : CS_Ping() {
    *this = ::std::move(from);
  }

  inline CS_Ping& operator=(CS_Ping&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CS_Ping& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CS_Ping* internal_default_instance() {
    return reinterpret_cast<const CS_Ping*>(
               &_CS_Ping_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CS_Ping* other);
  friend void swap(CS_Ping& a, CS_Ping& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CS_Ping* New() const PROTOBUF_FINAL { return New(NULL); }

  CS_Ping* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CS_Ping& from);
  void MergeFrom(const CS_Ping& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CS_Ping* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string param = 1;
  bool has_param() const;
  void clear_param();
  static const int kParamFieldNumber = 1;
  const ::std::string& param() const;
  void set_param(const ::std::string& value);
  #if LANG_CXX11
  void set_param(::std::string&& value);
  #endif
  void set_param(const char* value);
  void set_param(const char* value, size_t size);
  ::std::string* mutable_param();
  ::std::string* release_param();
  void set_allocated_param(::std::string* param);

  // @@protoc_insertion_point(class_scope:proto.CS_Ping)
 private:
  void set_has_param();
  void clear_has_param();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr param_;
  friend struct ::protobuf_connector_2eproto::TableStruct;
  friend void ::protobuf_connector_2eproto::InitDefaultsCS_PingImpl();
};
// -------------------------------------------------------------------

class SC_RetPing : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.SC_RetPing) */ {
 public:
  SC_RetPing();
  virtual ~SC_RetPing();

  SC_RetPing(const SC_RetPing& from);

  inline SC_RetPing& operator=(const SC_RetPing& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SC_RetPing(SC_RetPing&& from) noexcept
    : SC_RetPing() {
    *this = ::std::move(from);
  }

  inline SC_RetPing& operator=(SC_RetPing&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SC_RetPing& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SC_RetPing* internal_default_instance() {
    return reinterpret_cast<const SC_RetPing*>(
               &_SC_RetPing_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(SC_RetPing* other);
  friend void swap(SC_RetPing& a, SC_RetPing& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SC_RetPing* New() const PROTOBUF_FINAL { return New(NULL); }

  SC_RetPing* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SC_RetPing& from);
  void MergeFrom(const SC_RetPing& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SC_RetPing* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string ret_param = 1;
  bool has_ret_param() const;
  void clear_ret_param();
  static const int kRetParamFieldNumber = 1;
  const ::std::string& ret_param() const;
  void set_ret_param(const ::std::string& value);
  #if LANG_CXX11
  void set_ret_param(::std::string&& value);
  #endif
  void set_ret_param(const char* value);
  void set_ret_param(const char* value, size_t size);
  ::std::string* mutable_ret_param();
  ::std::string* release_ret_param();
  void set_allocated_ret_param(::std::string* ret_param);

  // @@protoc_insertion_point(class_scope:proto.SC_RetPing)
 private:
  void set_has_ret_param();
  void clear_has_ret_param();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr ret_param_;
  friend struct ::protobuf_connector_2eproto::TableStruct;
  friend void ::protobuf_connector_2eproto::InitDefaultsSC_RetPingImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CS_Ping

// optional string param = 1;
inline bool CS_Ping::has_param() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CS_Ping::set_has_param() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CS_Ping::clear_has_param() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CS_Ping::clear_param() {
  param_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_param();
}
inline const ::std::string& CS_Ping::param() const {
  // @@protoc_insertion_point(field_get:proto.CS_Ping.param)
  return param_.GetNoArena();
}
inline void CS_Ping::set_param(const ::std::string& value) {
  set_has_param();
  param_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.CS_Ping.param)
}
#if LANG_CXX11
inline void CS_Ping::set_param(::std::string&& value) {
  set_has_param();
  param_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.CS_Ping.param)
}
#endif
inline void CS_Ping::set_param(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_param();
  param_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.CS_Ping.param)
}
inline void CS_Ping::set_param(const char* value, size_t size) {
  set_has_param();
  param_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.CS_Ping.param)
}
inline ::std::string* CS_Ping::mutable_param() {
  set_has_param();
  // @@protoc_insertion_point(field_mutable:proto.CS_Ping.param)
  return param_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CS_Ping::release_param() {
  // @@protoc_insertion_point(field_release:proto.CS_Ping.param)
  clear_has_param();
  return param_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CS_Ping::set_allocated_param(::std::string* param) {
  if (param != NULL) {
    set_has_param();
  } else {
    clear_has_param();
  }
  param_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), param);
  // @@protoc_insertion_point(field_set_allocated:proto.CS_Ping.param)
}

// -------------------------------------------------------------------

// SC_RetPing

// optional string ret_param = 1;
inline bool SC_RetPing::has_ret_param() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SC_RetPing::set_has_ret_param() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SC_RetPing::clear_has_ret_param() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SC_RetPing::clear_ret_param() {
  ret_param_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_ret_param();
}
inline const ::std::string& SC_RetPing::ret_param() const {
  // @@protoc_insertion_point(field_get:proto.SC_RetPing.ret_param)
  return ret_param_.GetNoArena();
}
inline void SC_RetPing::set_ret_param(const ::std::string& value) {
  set_has_ret_param();
  ret_param_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.SC_RetPing.ret_param)
}
#if LANG_CXX11
inline void SC_RetPing::set_ret_param(::std::string&& value) {
  set_has_ret_param();
  ret_param_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.SC_RetPing.ret_param)
}
#endif
inline void SC_RetPing::set_ret_param(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_ret_param();
  ret_param_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.SC_RetPing.ret_param)
}
inline void SC_RetPing::set_ret_param(const char* value, size_t size) {
  set_has_ret_param();
  ret_param_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.SC_RetPing.ret_param)
}
inline ::std::string* SC_RetPing::mutable_ret_param() {
  set_has_ret_param();
  // @@protoc_insertion_point(field_mutable:proto.SC_RetPing.ret_param)
  return ret_param_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SC_RetPing::release_ret_param() {
  // @@protoc_insertion_point(field_release:proto.SC_RetPing.ret_param)
  clear_has_ret_param();
  return ret_param_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SC_RetPing::set_allocated_ret_param(::std::string* ret_param) {
  if (ret_param != NULL) {
    set_has_ret_param();
  } else {
    clear_has_ret_param();
  }
  ret_param_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ret_param);
  // @@protoc_insertion_point(field_set_allocated:proto.SC_RetPing.ret_param)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_connector_2eproto__INCLUDED
