// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

#include "connector.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace proto {
class CS_PingDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CS_Ping>
      _instance;
} _CS_Ping_default_instance_;
class SC_RetPingDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SC_RetPing>
      _instance;
} _SC_RetPing_default_instance_;
}  // namespace proto
namespace protobuf_connector_2eproto {
void InitDefaultsCS_PingImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::proto::_CS_Ping_default_instance_;
    new (ptr) ::proto::CS_Ping();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::CS_Ping::InitAsDefaultInstance();
}

void InitDefaultsCS_Ping() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsCS_PingImpl);
}

void InitDefaultsSC_RetPingImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::proto::_SC_RetPing_default_instance_;
    new (ptr) ::proto::SC_RetPing();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::SC_RetPing::InitAsDefaultInstance();
}

void InitDefaultsSC_RetPing() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSC_RetPingImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::CS_Ping, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::CS_Ping, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::CS_Ping, param_),
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::SC_RetPing, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::SC_RetPing, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::SC_RetPing, ret_param_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::proto::CS_Ping)},
  { 7, 13, sizeof(::proto::SC_RetPing)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_CS_Ping_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_SC_RetPing_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "connector.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017connector.proto\022\005proto\"\030\n\007CS_Ping\022\r\n\005p"
      "aram\030\001 \001(\t\"\037\n\nSC_RetPing\022\021\n\tret_param\030\001 "
      "\001(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 83);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "connector.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_connector_2eproto
namespace proto {

// ===================================================================

void CS_Ping::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CS_Ping::kParamFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CS_Ping::CS_Ping()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_connector_2eproto::InitDefaultsCS_Ping();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.CS_Ping)
}
CS_Ping::CS_Ping(const CS_Ping& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  param_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_param()) {
    param_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.param_);
  }
  // @@protoc_insertion_point(copy_constructor:proto.CS_Ping)
}

void CS_Ping::SharedCtor() {
  _cached_size_ = 0;
  param_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

CS_Ping::~CS_Ping() {
  // @@protoc_insertion_point(destructor:proto.CS_Ping)
  SharedDtor();
}

void CS_Ping::SharedDtor() {
  param_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CS_Ping::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CS_Ping::descriptor() {
  ::protobuf_connector_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_connector_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CS_Ping& CS_Ping::default_instance() {
  ::protobuf_connector_2eproto::InitDefaultsCS_Ping();
  return *internal_default_instance();
}

CS_Ping* CS_Ping::New(::google::protobuf::Arena* arena) const {
  CS_Ping* n = new CS_Ping;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CS_Ping::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.CS_Ping)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(!param_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*param_.UnsafeRawStringPointer())->clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool CS_Ping::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.CS_Ping)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string param = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_param()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->param().data(), static_cast<int>(this->param().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "proto.CS_Ping.param");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.CS_Ping)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.CS_Ping)
  return false;
#undef DO_
}

void CS_Ping::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.CS_Ping)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string param = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->param().data(), static_cast<int>(this->param().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto.CS_Ping.param");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->param(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.CS_Ping)
}

::google::protobuf::uint8* CS_Ping::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.CS_Ping)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string param = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->param().data(), static_cast<int>(this->param().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto.CS_Ping.param");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->param(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.CS_Ping)
  return target;
}

size_t CS_Ping::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.CS_Ping)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // optional string param = 1;
  if (has_param()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->param());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CS_Ping::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.CS_Ping)
  GOOGLE_DCHECK_NE(&from, this);
  const CS_Ping* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CS_Ping>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.CS_Ping)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.CS_Ping)
    MergeFrom(*source);
  }
}

void CS_Ping::MergeFrom(const CS_Ping& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.CS_Ping)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_param()) {
    set_has_param();
    param_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.param_);
  }
}

void CS_Ping::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.CS_Ping)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CS_Ping::CopyFrom(const CS_Ping& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.CS_Ping)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CS_Ping::IsInitialized() const {
  return true;
}

void CS_Ping::Swap(CS_Ping* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CS_Ping::InternalSwap(CS_Ping* other) {
  using std::swap;
  param_.Swap(&other->param_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CS_Ping::GetMetadata() const {
  protobuf_connector_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_connector_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SC_RetPing::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SC_RetPing::kRetParamFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SC_RetPing::SC_RetPing()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_connector_2eproto::InitDefaultsSC_RetPing();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.SC_RetPing)
}
SC_RetPing::SC_RetPing(const SC_RetPing& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ret_param_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_ret_param()) {
    ret_param_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ret_param_);
  }
  // @@protoc_insertion_point(copy_constructor:proto.SC_RetPing)
}

void SC_RetPing::SharedCtor() {
  _cached_size_ = 0;
  ret_param_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

SC_RetPing::~SC_RetPing() {
  // @@protoc_insertion_point(destructor:proto.SC_RetPing)
  SharedDtor();
}

void SC_RetPing::SharedDtor() {
  ret_param_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SC_RetPing::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SC_RetPing::descriptor() {
  ::protobuf_connector_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_connector_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SC_RetPing& SC_RetPing::default_instance() {
  ::protobuf_connector_2eproto::InitDefaultsSC_RetPing();
  return *internal_default_instance();
}

SC_RetPing* SC_RetPing::New(::google::protobuf::Arena* arena) const {
  SC_RetPing* n = new SC_RetPing;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SC_RetPing::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.SC_RetPing)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(!ret_param_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*ret_param_.UnsafeRawStringPointer())->clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SC_RetPing::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.SC_RetPing)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string ret_param = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ret_param()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->ret_param().data(), static_cast<int>(this->ret_param().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "proto.SC_RetPing.ret_param");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.SC_RetPing)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.SC_RetPing)
  return false;
#undef DO_
}

void SC_RetPing::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.SC_RetPing)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string ret_param = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ret_param().data(), static_cast<int>(this->ret_param().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto.SC_RetPing.ret_param");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->ret_param(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.SC_RetPing)
}

::google::protobuf::uint8* SC_RetPing::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.SC_RetPing)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string ret_param = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ret_param().data(), static_cast<int>(this->ret_param().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto.SC_RetPing.ret_param");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->ret_param(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.SC_RetPing)
  return target;
}

size_t SC_RetPing::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.SC_RetPing)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // optional string ret_param = 1;
  if (has_ret_param()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ret_param());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SC_RetPing::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.SC_RetPing)
  GOOGLE_DCHECK_NE(&from, this);
  const SC_RetPing* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SC_RetPing>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.SC_RetPing)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.SC_RetPing)
    MergeFrom(*source);
  }
}

void SC_RetPing::MergeFrom(const SC_RetPing& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.SC_RetPing)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_ret_param()) {
    set_has_ret_param();
    ret_param_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ret_param_);
  }
}

void SC_RetPing::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.SC_RetPing)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SC_RetPing::CopyFrom(const SC_RetPing& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.SC_RetPing)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SC_RetPing::IsInitialized() const {
  return true;
}

void SC_RetPing::Swap(SC_RetPing* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SC_RetPing::InternalSwap(SC_RetPing* other) {
  using std::swap;
  ret_param_.Swap(&other->ret_param_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SC_RetPing::GetMetadata() const {
  protobuf_connector_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_connector_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto

// @@protoc_insertion_point(global_scope)
